export interface OrderInterface {
	car?:Array<string>;	
	className?:string;
	tittle?:string;
	start?:string;
	date?:string;
	currency?:string;
	email?:string;
	direccion?:string;
	id?:number;
	metodo?:string;
	personaContacto?:string;
	status?:string;
	telefono?:string;
	total?:number;
	npedido?:string;
	steeps?:Array<any>;	
	pagoImage?:Array<string>;
}
